# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d520d06b9692284f00803b2dca3af37c7b18126aff0ffc8cfd12a770900de8ab19184b8bc984efef63d7114d324e2ec76ee074267eb08c0e09d2975e8b0026d

test:
  secret_key_base: df8ccfb25276f8ce7c974fb0cd2581836f0b03e2cff7ccde8ca6f8180c33cb8285796da6137b160ec39a7f3cea699ca6aad96fc2eb858ff9d0af5eaa92613764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
